security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/user/, roles: ROLE_USER }

    providers:
        in_memory:
            memory:
                users:
                    jmonti: { password: 1234, roles: 'ROLE_USER' }
                    mparra: { password: 12345, roles: 'ROLE_USER' }
