security:
    encoders:
        prog3\AppunteBundle\Entity\Usuario:
            algorithm: bcrypt

    role_hierarchy:
            ROLE_ADMIN:       ROLE_USER

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~
            logout: ~

    access_control:
        - { path: ^/user/, roles: ROLE_USER }

    providers:
        bd_users:
            entity: { class: prog3AppunteBundle:Usuario, property: username }
