prog3_appunte_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: prog3AppunteBundle:Default:index }

prog3_appunte_home:
    pattern:  /
    defaults: { _controller: prog3AppunteBundle:Home:index }